=== MatfUVIT/primeri-predavanja/sgml-dtd-xml/p04-xml-shema/p10-kljuc-referenca/z01-porudzbine/porudzbina-structure.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="porudzbina" type="PorudzbinaType">
        <xsd:keyref name="brojProizvodaKeyRef" refer="brojProizvodaKey">
            <xsd:selector xpath="elelmenti/*" />
            <xsd:field xpath="@broj" />
        </xsd:keyref>
        <xsd:key name="brojProizvodaKey">
            <xsd:selector xpath=".//proizvod" />
            <xsd:field xpath="broj" />
        </xsd:key>
    </xsd:element>
    <xsd:complexType name="PorudzbinaType">
        <xsd:sequence>
            <xsd:element name="broj" type="xsd:string" />
            <xsd:element name="elementi" type="ElementiType" />
            <xsd:element name="proizvodi" type="ProizvodiType" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ElementiType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="kosulja" type="ProizvodPorudzbinaType" />
            <xsd:element name="kapa" type="ProizvodPorudzbinaType" />
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="ProizvodPorudzbinaType">
        <xsd:sequence>
            <xsd:element name="kolicina" type="xsd:integer" />
            <xsd:element name="boja" type="BojaType" minOccurs="0" />
        </xsd:sequence>
        <xsd:attribute name="broj" type="xsd:integer" />
    </xsd:complexType>
    <xsd:complexType name="ProizvodiType">
        <xsd:sequence>
            <xsd:element name="proizvod" type="ProizvodType"
                maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="ProizvodType">
        <xsd:sequence>
            <xsd:element name="broj" type="xsd:integer" />
            <xsd:element name="naziv" type="xsd:string" />
            <xsd:element name="cena" type="CenaType" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="BojaType">
        <xsd:attribute name="opis" type="xsd:string" />
    </xsd:complexType>
    <xsd:complexType name="CenaType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:decimal">
                <xsd:attribute name="valuta" type="xsd:token" />
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
</xsd:schema>

=== MatfUVIT/primeri-predavanja/sgml-dtd-xml/p04-xml-shema/p10-kljuc-referenca/z01-porudzbine/porudzbina.xml
<porudzbina xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="porudzbina-structure.xsd">
    <broj>123ABBCC123</broj>
    <elementi>
        <kosulja broj="525">
            <kolicina>4</kolicina>
            <boja opis="plava" />
        </kosulja>
        <kosulja broj="520">
            <kolicina>1</kolicina>
            <boja opis="siva" />
        </kosulja>
        <kapa broj="533">
            <kolicina>1</kolicina>
        </kapa>
    </elementi>
    <proizvodi>
        <proizvod>
            <broj>525</broj>
            <naziv>Short-Sleeved Linen Blouse</naziv>
            <cena valuta="USD">29.99</cena>
        </proizvod>
        <proizvod>
            <broj>533</broj>
            <naziv>Ten-Gallon Hat</naziv>
            <cena valuta="USD">69.99</cena>
        </proizvod>
        <proizvod>
            <broj>520</broj>
            <naziv>plava kosialja</naziv>
            <cena valuta="USD">69.99</cena>
        </proizvod>
    </proizvodi>
</porudzbina>
